language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
before_install: 
- gem install bundler
- curl -sSL "https://github.com/aubio/aubio/archive/0.4.9.tar.gz" | tar zxvf -
- sudo apt update -y && sudo apt install -y libavcodec-dev libavutil-dev libavformat-dev libswresample-dev libavresample-dev libsamplerate-dev libsndfile-dev txt2man doxygen
- cd aubio-0.4.9
- make
- ./scripts/get_waf.sh
- ./waf configure
- ./waf build
- sudo ./waf install
script: bundle && bundle exec rake test
